app/Http/routes.php
<?php
use Illuminate\Http\Request;
use GoTest\PreguntaOrden;
use GoTest\RespuestaOrden;
use GoTest\PreguntaComplementacion;
use GoTest\RespuestaComplementacion;
use GoTest\Categoria;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//Mauricio Trigo
Route::resource('/', 'HomeController');
Route::get('/home','HomeController@home');
Route::resource('pregunta','PreguntaFrontController');
Route::get('pregunta/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');


Route::resource('abierta','PreguntaAbiertaController');
Route::get('abierta/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('abierta/{abierta}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('abierta/{abierta}/destroy',[
  'uses'=>'PreguntaAbiertaController@destroy',
  'as' => 'abierta.destroy'
]);

Route::get('subcategoria/{subcategoria}','CategoriaController@getSubCategorias');

Route::resource('seleccion-simple','PreguntaSeleccionSimpleController');
Route::get('seleccion-simple/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('seleccion-simple/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('seleccion-simple/{seleccion}/destroy',[
  'uses'=>'PreguntaSeleccionSimpleController@destroy',
  'as' => 'seleccion-simple.destroy'
]);

Route::resource('falso-verdadero','PreguntaFalsoVerdaderoController');
Route::get('falso-verdadero/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('falso-verdadero/{falsoverdadero}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('falso-verdadero/{falsoverdadero}/destroy',[
  'uses'=>'PreguntaFalsoVerdaderoController@destroy',
  'as' => 'falso-verdadero.destroy'
]);

Route::resource('opciones','SeleccionSimpleOpcionesController');

Route::resource('ordenamiento','PreguntaOrdenamientoController');
Route::get('ordenamiento/{ordenamiento}/edit',[
  'uses'=>'PreguntaOrdenamientoController@edit',
  'as' => 'ordenamiento.edit'
]);
Route::get('ordenamiento/{ordenamiento}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('ordenamiento/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('ordenamiento/{ordenamiento}/destroy',[
  'uses'=>'PreguntaOrdenamientoController@destroy',
  'as' => 'ordenamiento.destroy'
]);
Route::resource('opcionesorden','OrdenamientoOpcionesController');

Route::resource('preguntas/listar','PreguntaFrontController');

Route::resource('seleccion-multiple','PreguntaSeleccionMultipleController');
Route::get('seleccion-multiple/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('seleccion-multiple/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('seleccion-multiple/{seleccion}/destroy',[
  'uses'=>'PreguntaSeleccionMultipleController@destroy',
  'as' => 'seleccion-multiple.destroy'
]);

Route::resource('opciones-multiple','SeleccionMultipleOpcionesController');

Route::resource('correccion-falso-verdadero','RespuestasFalsoVerdaderoController');
Route::get('correccion-falso-verdadero/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('correccion-falso-verdadero/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('correccion-falso-verdadero/{seleccion}/destroy',[
  'uses'=>'RespuestasFalsoVerdaderoController@destroy',
  'as' => 'correccion-falso-verdadero.destroy'
]);

Route::resource('correccion-abiertas','RespuestaPreguntaAbiertaController');
Route::get('correccion-abiertas/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('correccion-abiertas/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('correccion-abiertas/{seleccion}/destroy',[
  'uses'=>'RespuestaPreguntaAbiertaController@destroy',
  'as' => 'correccion-abiertas.destroy'
]);

Route::resource('correccion-sel-simple','RespuestaSeleccionSimpleController');
Route::get('correccion-sel-simple/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('correccion-sel-simple/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('correccion-sel-simple/{seleccion}/destroy',[
  'uses'=>'RespuestaSeleccionSimpleController@destroy',
  'as' => 'correccion-sel-simple.destroy'
]);

Route::resource('correccion-ordenamiento','RespuestaOrdenamientoController');
Route::get('correccion-ordenamiento/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('correccion-ordenamiento/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('correccion-ordenamiento/{seleccion}/destroy',[
  'uses'=>'RespuestaOrdenamientoController@destroy',
  'as' => 'correccion-ordenamiento.destroy'
]);
Route::resource('usuarios','UsuarioController');

Route::resource('login','LoginController');
Route::get('logout','LoginController@logout');
//Mau Trigo

//Roger
Route::resource('respuestaSeleccion','RespuestaSelMultipleController');
Route::get('respuestaSelecion/{id}/create',[
  'uses' => 'RespuestaSelMultipleController@create',
  'as'   => 'respuestaSeleccion.create'
]);
Route::resource('resolver-emparejamiento','CorreccionEmparejamientoController');
Route::get('resolver-emparejamiento/{id}/create',[
  'uses' => 'CorreccionEmparejamientoController@create',
  'as'   => 'resolver-emparejamiento.create'
]);
//Roger

//Daniela
// complementacion

Route::get('/pregunta-complementacion', function(){
    $preguntas = PreguntaComplementacion::all();
    return view('preguntacomplementacion.listar', array(
        'preguntas' => $preguntas
    ));

});

Route::get('/crear-pregunta-complementacion', function( ){
    $categorias = Categoria::all();
     return view('preguntacomplementacion.create', array(
        'categorias' => $categorias
    ));
});

Route::post('/crear-pregunta-complementacion', function(Request $request){
    $rules = array(
        'enunciado' => 'required|max:255|min:6',
    );
    $mensajes = array(
        'required' => 'El campo :attribute es requerido',
        'min' => 'El campo :attribute debe ser mayor a 6 caracteres'

    );
    $validator = Validator::make($request->all(), $rules, $mensajes);
    if($validator->fails()) {
      return redirect('/crear-pregunta-complementacion')
        ->withInput()
        ->withErrors($validator);
    }
    $respuestas = $request->respuestas;
    $rules = array(
        'palabra clave' => 'required',
    );
    for ($i = 0; $i < count($respuestas) ; $i++) {
        $valores = array(
            'palabra clave' => $respuestas[$i],
        );
        $validator = Validator::make($valores, $rules, $mensajes);
        if($validator->fails()) {
            return redirect('/crear-pregunta-complementacion')
            ->withInput()
            ->withErrors($validator);
        }
    }

    $pregunta = new PreguntaComplementacion;
    $pregunta->enunciado = $request->enunciado;
    $pregunta->usuarios_id = $request->usuarios_id;
    if($request->subcategoria) {
        $pregunta->subcategoria_id = $request->subcategoria;
    } else {
        $pregunta->subcategoria_id = null;
    }
    //$pregunta->subcategoria_id = $request->subcategoria;
    $pregunta->save();
    for ($i = 0; $i < count($respuestas) ; $i++) {
        $respuesta = new RespuestaComplementacion;
        $respuesta->respuesta = $respuestas[$i];
        $respuesta->pregunta_complementacion_id = $pregunta->id;
        $respuesta->save();
    }
    return redirect('/ver-pregunta-complementacion/' . $pregunta->id);
});
Route::get('/editar-pregunta-complementacion/{pregunta}', function( PreguntaComplementacion $pregunta ){
    $categorias = Categoria::all();
    return view('preguntacomplementacion.editar', array(
        'pregunta' => $pregunta,
        'categorias' => $categorias
    ));
});

Route::post('/editar-pregunta-complementacion/{pregunta}', function(Request $request, PreguntaComplementacion $pregunta){
    $rules = array(
        'enunciado' => 'required|max:255|min:6',
    );
    $mensajes = array(
        'required' => 'El campo :attribute es requerido',
        'min' => 'El campo :attribute debe ser mayor a 6 caracteres'

    );
    $validator = Validator::make($request->all(), $rules, $mensajes);
    if($validator->fails()) {
      return redirect('/editar-pregunta-complementacion' . $pregunta->id)
        ->withInput()
        ->withErrors($validator);
    }
    $respuestas = $request->respuestas;
    $rules = array(
        'palabra clave' => 'required',
    );
    for ($i = 0; $i < count($respuestas) ; $i++) {
        $valores = array(
            'palabra clave' => $respuestas[$i],
        );
        $validator = Validator::make($valores, $rules, $mensajes);
        if($validator->fails()) {
            return redirect('/editar-pregunta-complementacion' . $pregunta->id)
            ->withInput()
            ->withErrors($validator);
        }
    }

    $pregunta->enunciado = $request->enunciado;
    //$pregunta->subcategoria_id = $request->subcategoria;
    if($request->subcategoria) {
        $pregunta->subcategoria_id = $request->subcategoria;
    } else {
        $pregunta->subcategoria_id = null;
    }
    $pregunta->save();
    foreach ($pregunta->respuestas as $respuesta) {
        $respuesta->delete();
    }

    for ($i = 0; $i < count($respuestas) ; $i++) {
        $respuesta = new RespuestaComplementacion;
        $respuesta->respuesta = $respuestas[$i];

resources/views/preguntageneral/index.blade.php
@extends('layouts.principal')
@section('content')
  {!!Html::style('css/tooltips.css')!!}
  <div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">Preguntas registradas</h1>
  </div>
  <!-- /.col-lg-12 -->
  </div>
  <div class="row">
      <div class="col-lg-12">
          <div class="panel panel-default">
              <div class="panel-heading">
                  Preguntas registradas en la base de datos
              </div>
              <!-- /.panel-heading -->
              <div class="panel-body">
                  <div class="dataTable_wrapper">
                      <table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example" role="grid" aria-describedby="dataTables-example_info">
                        <thead>
                            <tr role="row">
                              <th class="sorting_asc" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1"
                                  aria-label="Rendering engine: activate to sort column descending" aria-sort="ascending" style="width: 172px;">Tipo pregunta
                              </th>
                              <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1"
                                  aria-label="Browser: activate to sort column ascending" style="width: 204px;">Enunciado
                              </th>
                              <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1"
                                  aria-label="Platform(s): activate to sort column ascending" style="width: 105px;">Categoria
                              </th>
                              <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1"
                                  aria-label="Engine version: activate to sort column ascending" style="width: 145px;">Subcategoria
                              </th>
                              <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1"
                                  aria-label="CSS grade: activate to sort column ascending" style="width: 110px;">Fecha creación
                              </th>
                              <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1"
                                  aria-label="CSS grade: activate to sort column ascending" style="width: 60px;">Acción
                              </th>
                            </tr>
                        </thead>
                        @foreach($preguntas as $pregunta)
                        <tbody>
                        <tr class="gradeA odd" role="row">
                          <td>{{$pregunta->tipo}}</td>
                          <td>{{str_limit($pregunta->enunciado,$limit = 50,$end='...')}}</td>
                          <td>{{$pregunta->categoria}}</td>
                          <td>{{$pregunta->subcategoria}}</td>
                          <td>{{$pregunta->created_at}}</td>
                          @if($pregunta->alias == "preg_abierta")
                            {{-- <td>{!!link_to_route('abierta.edit', $title = 'Editar', $parameters = $pregunta->id, $attributes = ['class'=>'btn btn-outline btn-primary'])!!} --}}
                           <td>
                                <a href="{!! URL::route('abierta.edit', array($pregunta->id)) !!}" class="btn btn-primary btn-circle" data-tooltip="Editar pregunta"><i class="fa fa-list"></i></a>
                                <a href="{!! URL::route('abierta.destroy', array($pregunta->id)) !!}" class="btn btn-danger btn-circle" data-tooltip="Eliminar pregunta" onclick='return confirm("¿Estas seguro de querer eliminar?")'><i class="fa fa-times"></i></a>
                           </td>
                          @endif
                          @if($pregunta->alias == "preg_fv")
                            <td>
                                 <a href="{!! URL::route('falso-verdadero.edit', array($pregunta->id)) !!}" class="btn btn-primary btn-circle" data-tooltip="Editar pregunta"><i class="fa fa-list"></i></a>
                                 <a href="{!! URL::route('falso-verdadero.destroy', array($pregunta->id)) !!}" class="btn btn-danger btn-circle" data-tooltip="Eliminar pregunta" onclick='return confirm("¿Estas seguro de querer eliminar?")'><i class="fa fa-times"></i></a>
                            </td>
                          @endif
                          @if($pregunta->alias == "preg_ordenamiento")
                            <td>
                                 <a href="{!! URL::route('ordenamiento.edit', array($pregunta->id)) !!}" class="btn btn-primary btn-circle" data-tooltip="Editar pregunta"><i class="fa fa-list"></i></a>
                                 <a href="{!! URL::route('ordenamiento.destroy', array($pregunta->id)) !!}" class="btn btn-danger btn-circle" data-tooltip="Eliminar pregunta" onclick='return confirm("¿Estas seguro de querer eliminar?")'><i class="fa fa-times"></i></a>
                            </td>
                          @endif
                          @if($pregunta->alias == "preg_sel_simple")
                            <td>
                                 <a href="{!! URL::route('seleccion-simple.edit', array($pregunta->id)) !!}" class="btn btn-primary btn-circle" data-tooltip="Editar pregunta"><i class="fa fa-list"></i></a>
                                 <a href="{!! URL::route('seleccion-simple.destroy', array($pregunta->id)) !!}" class="btn btn-danger btn-circle" data-tooltip="Eliminar pregunta" onclick='return confirm("¿Estas seguro de querer eliminar?")'><i class="fa fa-times"></i></a>
                            </td>
                          @endif
                          @if($pregunta->alias == "preg_sel_multiple")
                            <td>
                                 <a href="{!! URL::route('seleccion-multiple.edit', array($pregunta->id)) !!}" class="btn btn-primary btn-circle" data-tooltip="Editar pregunta"><i class="fa fa-list"></i></a>
                                 <a href="{!! URL::route('seleccion-simple.destroy', array($pregunta->id)) !!}" class="btn btn-danger btn-circle" data-tooltip="Eliminar pregunta" onclick='return confirm("¿Estas seguro de querer eliminar?")'><i class="fa fa-times"></i></a>
                            </td>
                          @endif
                          @if($pregunta->alias == "preg_complecion")
                            <td>
                                 <a href="{{ url('editar-pregunta-complementacion/'. $pregunta->id) }}" class="btn btn-primary btn-circle" data-tooltip="Editar pregunta"><i class="fa fa-list"></i></a>
                                 <a href="{{ url('eliminar-pregunta-complementacion/'. $pregunta->id) }}" class="btn btn-danger btn-circle" data-tooltip="Eliminar pregunta" onclick='return confirm("¿Estas seguro de querer eliminar?")'><i class="fa fa-times"></i></a>
                            </td>
                          @endif
                          @if($pregunta->alias == "preg_emparejamiento")
                            <td>
                                 <a href="#" class="btn btn-primary btn-circle" data-tooltip="Editar pregunta"><i class="fa fa-list"></i></a>
                                 <a href="#" class="btn btn-danger btn-circle" data-tooltip="Eliminar pregunta" onclick='return confirm("¿Estas seguro de querer eliminar?")'><i class="fa fa-times"></i></a>
                            </td>
                          @endif
                        </tr>
                        </tbody>
                        @endforeach
                      </table>
                      {!!$preguntas->render()!!}
                      {{-- {!!$preguntas->render()!!} --}}
                      @include('alerts.success')
                      @include('alerts.required')
                  </div>
              </div>
            </div>
          </div>
        </div>
@endsection