app/Http/routes.php
<?php
use Illuminate\Http\Request;
use GoTest\PreguntaOrden;
use GoTest\RespuestaOrden;
use GoTest\PreguntaComplementacion;
use GoTest\RespuestaComplementacion;
use GoTest\Categoria;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//Mauricio Trigo
Route::resource('/', 'HomeController');
Route::get('/home','HomeController@home');
Route::resource('pregunta','PreguntaFrontController');
Route::get('pregunta/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');


Route::resource('abierta','PreguntaAbiertaController');
Route::get('abierta/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('abierta/{abierta}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('abierta/{abierta}/destroy',[
  'uses'=>'PreguntaAbiertaController@destroy',
  'as' => 'abierta.destroy'
]);

Route::get('subcategoria/{subcategoria}','CategoriaController@getSubCategorias');

Route::resource('seleccion-simple','PreguntaSeleccionSimpleController');
Route::get('seleccion-simple/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('seleccion-simple/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('seleccion-simple/{seleccion}/destroy',[
  'uses'=>'PreguntaSeleccionSimpleController@destroy',
  'as' => 'seleccion-simple.destroy'
]);

Route::resource('falso-verdadero','PreguntaFalsoVerdaderoController');
Route::get('falso-verdadero/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('falso-verdadero/{falsoverdadero}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('falso-verdadero/{falsoverdadero}/destroy',[
  'uses'=>'PreguntaFalsoVerdaderoController@destroy',
  'as' => 'falso-verdadero.destroy'
]);

Route::resource('opciones','SeleccionSimpleOpcionesController');

Route::resource('ordenamiento','PreguntaOrdenamientoController');
Route::get('ordenamiento/{ordenamiento}/edit',[
  'uses'=>'PreguntaOrdenamientoController@edit',
  'as' => 'ordenamiento.edit'
]);
Route::get('ordenamiento/{ordenamiento}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('ordenamiento/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('ordenamiento/{ordenamiento}/destroy',[
  'uses'=>'PreguntaOrdenamientoController@destroy',
  'as' => 'ordenamiento.destroy'
]);
Route::resource('opcionesorden','OrdenamientoOpcionesController');

Route::resource('preguntas/listar','PreguntaFrontController');

Route::resource('seleccion-multiple','PreguntaSeleccionMultipleController');
Route::get('seleccion-multiple/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('seleccion-multiple/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('seleccion-multiple/{seleccion}/destroy',[
  'uses'=>'PreguntaSeleccionMultipleController@destroy',
  'as' => 'seleccion-multiple.destroy'
]);

Route::resource('opciones-multiple','SeleccionMultipleOpcionesController');

Route::resource('correccion-falso-verdadero','RespuestasFalsoVerdaderoController');
Route::get('correccion-falso-verdadero/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('correccion-falso-verdadero/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('correccion-falso-verdadero/{seleccion}/destroy',[
  'uses'=>'RespuestasFalsoVerdaderoController@destroy',
  'as' => 'correccion-falso-verdadero.destroy'
]);

Route::resource('correccion-abiertas','RespuestaPreguntaAbiertaController');
Route::get('correccion-abiertas/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('correccion-abiertas/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('correccion-abiertas/{seleccion}/destroy',[
  'uses'=>'RespuestaPreguntaAbiertaController@destroy',
  'as' => 'correccion-abiertas.destroy'
]);

Route::resource('correccion-sel-simple','RespuestaSeleccionSimpleController');
Route::get('correccion-sel-simple/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('correccion-sel-simple/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('correccion-sel-simple/{seleccion}/destroy',[
  'uses'=>'RespuestaSeleccionSimpleController@destroy',
  'as' => 'correccion-sel-simple.destroy'
]);

Route::resource('correccion-ordenamiento','RespuestaOrdenamientoController');
Route::get('correccion-ordenamiento/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('correccion-ordenamiento/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('correccion-ordenamiento/{seleccion}/destroy',[
  'uses'=>'RespuestaOrdenamientoController@destroy',
  'as' => 'correccion-ordenamiento.destroy'
]);
Route::resource('usuarios','UsuarioController');

Route::resource('login','LoginController');
Route::get('logout','LoginController@logout');
//Mau Trigo

//Roger
Route::resource('respuestaSeleccion','RespuestaSelMultipleController');
Route::get('respuestaSelecion/{id}/create',[
  'uses' => 'RespuestaSelMultipleController@create',
  'as'   => 'respuestaSeleccion.create'
]);
Route::resource('resolver-emparejamiento','CorreccionEmparejamientoController');
Route::get('resolver-emparejamiento/{id}/create',[
  'uses' => 'CorreccionEmparejamientoController@create',
  'as'   => 'resolver-emparejamiento.create'
]);
//Roger

//Daniela
// complementacion

Route::get('/pregunta-complementacion', function(){
    $preguntas = PreguntaComplementacion::all();
    return view('preguntacomplementacion.listar', array(
        'preguntas' => $preguntas
    ));

});

Route::get('/crear-pregunta-complementacion', function( ){
    $categorias = Categoria::all();
     return view('preguntacomplementacion.create', array(
        'categorias' => $categorias
    ));
});

Route::post('/crear-pregunta-complementacion', function(Request $request){
    $rules = array(
        'enunciado' => 'required|max:255|min:6',
    );
    $mensajes = array(
        'required' => 'El campo :attribute es requerido',
        'min' => 'El campo :attribute debe ser mayor a 6 caracteres'

    );
    $validator = Validator::make($request->all(), $rules, $mensajes);
    if($validator->fails()) {
      return redirect('/crear-pregunta-complementacion')
        ->withInput()
        ->withErrors($validator);
    }
    $respuestas = $request->respuestas;
    $rules = array(
        'palabra clave' => 'required',
    );
    for ($i = 0; $i < count($respuestas) ; $i++) {
        $valores = array(
            'palabra clave' => $respuestas[$i],
        );
        $validator = Validator::make($valores, $rules, $mensajes);
        if($validator->fails()) {
            return redirect('/crear-pregunta-complementacion')
            ->withInput()
            ->withErrors($validator);
        }
    }

    $pregunta = new PreguntaComplementacion;
    $pregunta->enunciado = $request->enunciado;
    $pregunta->usuarios_id = $request->usuarios_id;
    if($request->subcategoria) {
        $pregunta->subcategoria_id = $request->subcategoria;
    } else {
        $pregunta->subcategoria_id = null;
    }
    //$pregunta->subcategoria_id = $request->subcategoria;
    $pregunta->save();
    for ($i = 0; $i < count($respuestas) ; $i++) {
        $respuesta = new RespuestaComplementacion;
        $respuesta->respuesta = $respuestas[$i];
        $respuesta->pregunta_complementacion_id = $pregunta->id;
        $respuesta->save();
    }
    return redirect('/ver-pregunta-complementacion/' . $pregunta->id);
});
Route::get('/editar-pregunta-complementacion/{pregunta}', function( PreguntaComplementacion $pregunta ){
    $categorias = Categoria::all();
    return view('preguntacomplementacion.editar', array(
        'pregunta' => $pregunta,
        'categorias' => $categorias
    ));
});

Route::post('/editar-pregunta-complementacion/{pregunta}', function(Request $request, PreguntaComplementacion $pregunta){
    $rules = array(
        'enunciado' => 'required|max:255|min:6',
    );
    $mensajes = array(
        'required' => 'El campo :attribute es requerido',
        'min' => 'El campo :attribute debe ser mayor a 6 caracteres'

    );
    $validator = Validator::make($request->all(), $rules, $mensajes);
    if($validator->fails()) {
      return redirect('/editar-pregunta-complementacion' . $pregunta->id)
        ->withInput()
        ->withErrors($validator);
    }
    $respuestas = $request->respuestas;
    $rules = array(
        'palabra clave' => 'required',
    );
    for ($i = 0; $i < count($respuestas) ; $i++) {
        $valores = array(
            'palabra clave' => $respuestas[$i],
        );
        $validator = Validator::make($valores, $rules, $mensajes);
        if($validator->fails()) {
            return redirect('/editar-pregunta-complementacion' . $pregunta->id)
            ->withInput()
            ->withErrors($validator);
        }
    }

    $pregunta->enunciado = $request->enunciado;
    //$pregunta->subcategoria_id = $request->subcategoria;
    if($request->subcategoria) {
        $pregunta->subcategoria_id = $request->subcategoria;
    } else {
        $pregunta->subcategoria_id = null;
    }
    $pregunta->save();
    foreach ($pregunta->respuestas as $respuesta) {
        $respuesta->delete();
    }

    for ($i = 0; $i < count($respuestas) ; $i++) {
        $respuesta = new RespuestaComplementacion;
        $respuesta->respuesta = $respuestas[$i];

app/Http/Controllers/PreguntaSeleccionMultipleController.php
<?php

namespace GoTest\Http\Controllers;

use Illuminate\Http\Request;
use GoTest\PreguntaSeleccionMultiple;
use GoTest\SeleccionMultipleOpciones;
use GoTest\Categoria;
use GoTest\Http\Requests;
use Session;
use DB;
class PreguntaSeleccionMultipleController extends Controller
{
    public function __construct(){
      $this->middleware('usuario',['only'=>['create','store','update','destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $preguntas = PreguntaSeleccionMultiple::getAll();
      return view('preguntaseleccionmultiple.index',compact('preguntas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $categorias = Categoria::lists('categoria','id');
      //$subcategorias = SubCategoria::lists('categoria','id');
      return view('preguntaseleccionmultiple.create',compact('categorias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        PreguntaSeleccionMultiple::create($request->all());
         //ULTIMO REGISTRO Esto me regresa el campo como un arreglo y puedo accederlo como un string ->first()
        $last_record = DB::table('preguntas_seleccion_multiple')->select('id')
                                               ->orderBy('created_at', 'desc')
                                                ->take('1')
                                                ->first();
        // OK
        $pesos = 0;
        if(isset($request->contador)) 
          $pesos = 100/$request->contador;
        else $pesos = 2;
        $opciones = $request->opcion;
        $correctos = $request->correcto;

        for($i=0; $i < count($opciones); $i++) { 
            $opcion_obj = new SeleccionMultipleOpciones();
            $opcion_obj->opcion = $opciones[$i];
            if($correctos[$i] == '1'){
                $opcion_obj->peso = $pesos;
                $opcion_obj->correcto = 1;
            }
            else 
                $opcion_obj->peso = 0;
            $opcion_obj->preguntas_seleccion_multiple_id = $last_record->id;
            $opcion_obj->save();
        }
        Session::flash('store-success','Datos agregados correctamente!');
        return redirect()->route('seleccion-multiple.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $pregunta = PreguntaSeleccionMultiple::find($id);
      $subcategoria = DB::table('sub_categorias')->select('id','categoria')->where('categorias_id','=',$pregunta->categorias_id)->lists('categoria','id');
      $categoria = Categoria::lists('categoria','id');
      $obj = new SeleccionMultipleOpciones();
      $opcion = SeleccionMultipleOpciones::where('preguntas_seleccion_multiple_id','=',$pregunta->id)->get();
      $count = count($opcion);
      $correcto = $obj->getCorrectos($id);
      return view('preguntaseleccionmultiple.edit',['pregunta'=>$pregunta,'categoria'=>$categoria,
      'subcategoria'=>$subcategoria,'opcion'=>$opcion,'count2'=>$count]);//quitar count fv
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $id_opciones = $request->id_opciones;
        $correcto_old = $request->correcto;
        $opcion_old = $request->opcion;

        if(isset($request->correcto2) && isset($request->opcion2)){
           $correcto_new = $request->correcto2;
           $opcion_new = $request->opcion2;
           $pregunta = PreguntaSeleccionMultiple::find($id);
           $pregunta->enunciado = $request->enunciado;
           $pregunta->categorias_id = $request->categorias_id;
           $pregunta->subcategorias_id = $request->sub_categorias_id;

           for ($i=0; $i < count($id_opciones) ; $i++) { 
               $opcion_obj = SeleccionMultipleOpciones::find($id_opciones[$i]);
               $opcion_obj->opcion = $opcion_old[$i];
               $opcion_obj->correcto = $correcto_old[$i];
               $opcion_obj->preguntas_seleccion_multiple_id = $id;
               $opcion_obj->save();
           }

           for ($i=0; $i < count($correcto_new); $i++) { 
               $nuevas_opciones = new SeleccionMultipleOpciones();
               //echo $opcion_new[$i].":".$correcto_new[$i];
               $nuevas_opciones->opcion = $opcion_new[$i];
               $nuevas_opciones->correcto = $correcto_new[$i];
               $nuevas_opciones->preguntas_seleccion_multiple_id = $id;
               $nuevas_opciones->save();
           }
           Session::flash('update-success','Datos actualizados correctamente!');
           return redirect()->route('seleccion-multiple.index');
       }else{

           $pregunta = PreguntaSeleccionMultiple::find($id);
           $pregunta->enunciado = $request->enunciado;
           $pregunta->categorias_id = $request->categorias_id;
           $pregunta->subcategorias_id = $request->sub_categorias_id;

           for ($i=0; $i < count($id_opciones) ; $i++) { 
               $opcion_obj = SeleccionMultipleOpciones::find($id_opciones[$i]);
               $opcion_obj->opcion = $opcion_old[$i];
               $opcion_obj->correcto = $correcto_old[$i];
               $opcion_obj->preguntas_seleccion_multiple_id = $id;
               $opcion_obj->save();
           }
           Session::flash('update-success','Datos actualizados correctamente!');
           return redirect()->route('seleccion-multiple.index');
       }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pregunta = PreguntaSeleccionMultiple::find($id);
        $pregunta->delete();
        Session::flash('delete-success','Datos eliminados correctamente!');
        return redirect()->route('seleccion-multiple.index');
    }
}

resources/views/preguntaseleccionmultiple/create.blade.php
@extends('layouts.principal')
@section('content')
  <div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Registrar pregunta de seleccion multiple</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- /.row -->
<div class="panel-body">
<div class="row">
    <div class="col-lg-6">
@include('alerts.success')
@include('alerts.required')
{!!Html::style('css/style2.css')!!}
{!!Form::open(['route'=>'seleccion-multiple.store', 'method'=>'POST','onsubmit'=>'return ValidationEventSM()','files' => true])!!}
{!!Form::hidden('tipo', 'seleccion-multiple')!!}
{!!Form::hidden('usuarios_id', Auth::user()->id)!!}
@include('preguntaseleccion.form.pregunta')
{!!Form::close()!!}
</div>
</div>
<!-- /.col-lg-8 -->
<!-- /.col-lg-4 -->
</div>
@include('layouts.scripts')
@include('layouts.scripts-sel-multiple')
@endsection

resources/views/preguntaseleccionmultiple/create2.blade.php
@extends('layouts.principal')
@section('content')
    <div class="row">
      <div class="col-lg-12">
          <h1 class="page-header">Registrar pregunta</h1>
      </div>
      <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
  <!-- /.row -->
  <div class="panel-body">
  <div class="row">
      <div class="col-lg-6">
{!!Form::open(['route'=>'seleccion.store', 'method'=>'POST','files' => true])!!}
{!!Form::hidden('tipo', 'seleccion-simple')!!}
@include('preguntaseleccion.form.pregunta')
{!!Form::close()!!}
@include('layouts.scripts')
@include('layouts.scripts-sel-simple-create')
</div>
</div>
<!-- /.col-lg-8 -->
<!-- /.col-lg-4 -->
</div>
@endsection

resources/views/preguntaseleccionmultiple/edit.blade.php
@extends('layouts.principal')
@section('content')
  {!!Form::model($pregunta,['route'=>['seleccion-multiple.update',$pregunta->id],'method'=>'PUT','onsubmit'=>'return ValidationEventSM()','files' => true])!!} <!--enrutando los datos -->
  <div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Editar pregunta</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- /.row -->
<div class="panel-body">
<div class="row">
    <div class="col-lg-8">
      {!!Html::style('css/style2.css')!!}

      <!-- PREGUNTAS ABIERTAS -->
      {!!Form::hidden('tipo', 'seleccion-multiple')!!}
      {!!Form::label('categoria','Categoria: ')!!}
      {!!Form::select('categorias_id', $categoria,null,['id'=>'categoriaSelMultiple','class'=>'form-control',
                      'placeholder'=>'Seleccione una opcion..','required'])!!}<br>
      {!!Form::label('subcategoria','Sub-categoria: ')!!}
      {!!Form::select('sub_categorias_id', $subcategoria,null,['id'=>'subcategoriaSelMultiple','class'=>'form-control',
                      'placeholder'=>'Seleccione una opcion..','required'])!!}<br>
      {!!Form::label('enunciado','Enunciado: ')!!}
      {!!Form::textarea('enunciado',null,['class'=>'form-control', 'rows' => 2]) !!}<br>
      @include('alerts.error')
      {!!Form::label('opcion','Opciones de respuesta: ')!!}<br>
      @foreach($opcion as $key => $value)
        {{-- {!!Form::model($value,['route'=>['opciones.update',$value->id],'method'=>'PUT','id'=>'Form'.$a])!!} --}}
        <div class="form-group option-container-edit">
          {!!Form::hidden('id_opciones[]', $value->id)!!}
          <input id="count_old" type="hidden" name="contador" value="{{$count2}}">
            <div class="input-group ">
              @if($value->correcto == 1)
                <span class="input-group-addon">
                  {!!Form::select('correcto[]', ['1' => 'Correcto','0' => 'Incorrecto'],'default', ['id' => $value->id ])!!}
                </span>
              @else
                <span class="input-group-addon">
                  {!!Form::select('correcto[]', ['0' => 'Incorrecto','1' => 'Correcto'],'default', ['id' => $value->id ])!!}
                </span>
              @endif
                {!!Form::text('opcion[]',$value->opcion,['class'=>'form-control','min'=>'2','required']) !!}
              <span opcion-id="{{$value->id}}" class="input-group-btn">
                  <button class="btn btn-outline btn-danger btn-remove" type="button">X</button>
              </span>
            </div>
        </div>
      @endforeach
            <button type="button" class="btn btn-outline btn-success btn-lg btn-block btn-add-more-options-edit">Agregar opción</button>
            <h1 class="page-header"></h1>
            {{-- {!!link_to('#', $title='Actualizar', $attributes = ['id'=>'subbut', 'class'=>'btn btn-outline btn-primary'], $secure = null)!!} --}}
            {!!Form::submit('Actualizar',['class'=>'btn btn-outline btn-primary','id'=>'subbut'])!!}<br><br><br><br>
        </div>
    <!-- /.col-lg-8 -->
    <!-- /.col-lg-4 -->
</div>
</div>
{!!Form::close()!!}
{!!Form::open(['route'=>['opciones-multiple.destroy',':OPTION_ID'],'method'=>'DELETE','id'=>'form-delete'])!!}
{!!Form::close()!!}
<!-- /.row -->
@include('layouts.scripts')
@include('layouts.scripts-sel-multiple-edit')

@endsection

resources/views/preguntaseleccionmultiple/index.blade.php
@extends('layouts.principal')
@section('content')
  <div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">Preguntas registradas</h1>
  </div>
  <!-- /.col-lg-12 -->
  </div>
  <div class="row">
      <div class="col-lg-12">
          <div class="panel panel-default">
              <div class="panel-heading">
                  Preguntas registradas en la base de datos
                  <div class="pull-right">
                                <div class="btn-group">
                                    <a class="glyphicon-plus btn btn-outline btn-info btn-xs" href="{!!URL::to('seleccion-multiple/create')!!}"> Crear nueva</a>
                                </div>
                            </div>
                  </button>
              </div>
              <!-- /.panel-heading -->
              <div class="panel-body">
                  <div class="dataTable_wrapper">
                      <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                              <tr>
                                  <th>Enunciado</th>
                                  <th>Categoria</th>
                                  <th>Sub-categoria</th>
                                  <th>Fecha creacion</th>
                                  <th>Accion</th>
                              </tr>
                          </thead>
                          {{-- <tbody id="datos"> --}}
                            @foreach($preguntas as $pregunta)
                            <tbody>
                            <tr>
                              <td>{{str_limit($pregunta->enunciado,$limit = 30,$end='...')}}</td>
                              <td>{{$pregunta->categoria}}</td>
                              <td>{{$pregunta->subcategoria}}</td>
                              <td>{{$pregunta->created_at}}</td>
                              <td>
                                  <div class="form-group" align="center">
                                  <a href="{!! route('seleccion-multiple.edit',$parameters = $pregunta->id) !!}" class="btn btn-primary btn-circle" data-tooltip="Editar pregunta"><i class="glyphicon glyphicon-edit"></i></a>

                                  <a href="{!! route('respuestaSeleccion.create',$parameters = $pregunta->id) !!}" class="btn btn-warning btn-circle" data-tooltip="Resolver y corregir"><i class="fa fa-mortar-board "></i></a>

                                  <a href="{!! route('seleccion-multiple.destroy',$parameters = $pregunta->id) !!}" class="btn btn-danger btn-circle" data-tooltip="Eliminar pregunta" onclick='return confirm("¿Estas seguro de querer eliminar?")'><i class="glyphicon glyphicon-trash"></i></a></div>
                             </td>
                            </tr>
                            </tbody>
                            @endforeach
                          {{-- </tbody> --}}
                      </table>
                      {!!$preguntas->render()!!}
                      @include('alerts.success')
                      @include('alerts.required')
                  </div>
              </div>
            </div>
          </div>
        </div>
@endsection

resources/views/preguntaseleccionmultiple/show.blade.php
@extends('layouts.principal')
@section('content')
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Vista Previa de la Pregunta</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- /.row -->
<div class="panel-body">
  <div class="row">
    <div class="col-lg-6">
      @include('alerts.success')
      @include('alerts.required')
      <form action="{{ route('respuestaSeleccion.store') }}" method="POST" class="form-horizontal">
        {!! csrf_field() !!}
        <div class="">
          <label for="enunciado" class="control-label text-primary">{{ $pregunta->enunciado }}</label>
        </div>
        <div class="">
          <label for="enunciado" class="control-label ">Seleccione las Respuestas Correctas</label>
          @foreach($pregunta->opciones as $opcion)
          <div class="checkbox">
            <input type="checkbox" name="respuesta[]" value="{{ $opcion->id }}"> {{ $opcion->opcion }}
          </div>
          @endforeach
          {!!Form::hidden('idPregunta', $pregunta->id)!!}
        </div>
        <br>
        <div class="">
          <div class="">
            <button type="submit" class="btn btn-primary"> Añadir Respuesta
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <!-- /.col-lg-8 -->
  <!-- /.col-lg-4 -->
</div>
<!-- /.row -->
{!!Html::script('bower_components/jquery/dist/jquery.min.js')!!}
<!-- Bootstrap Core JavaScript -->
{!!Html::script('bower_components/bootstrap/dist/js/bootstrap.min.js')!!}
<!-- Metis Menu Plugin JavaScript -->
{!!Html::script('bower_components/metisMenu/dist/metisMenu.min.js')!!}
<!-- Morris Charts JavaScript -->
{!!Html::script('bower_components/raphael/raphael-min.js')!!}
{!!Html::script('bower_components/morrisjs/morris.min.js')!!}
{!!Html::script('js/morris-data.js')!!}
<!-- Custom Theme JavaScript -->
{!!Html::script('dist/js/sb-admin-2.js')!!}
@endsection