app/Http/routes.php
<?php
use Illuminate\Http\Request;
use GoTest\PreguntaOrden;
use GoTest\RespuestaOrden;
use GoTest\PreguntaComplementacion;
use GoTest\RespuestaComplementacion;
use GoTest\Categoria;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//Mauricio Trigo
Route::resource('/', 'HomeController');
Route::get('/home','HomeController@home');
Route::resource('pregunta','PreguntaFrontController');
Route::get('pregunta/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');


Route::resource('abierta','PreguntaAbiertaController');
Route::get('abierta/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('abierta/{abierta}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('abierta/{abierta}/destroy',[
  'uses'=>'PreguntaAbiertaController@destroy',
  'as' => 'abierta.destroy'
]);

Route::get('subcategoria/{subcategoria}','CategoriaController@getSubCategorias');

Route::resource('seleccion-simple','PreguntaSeleccionSimpleController');
Route::get('seleccion-simple/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('seleccion-simple/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('seleccion-simple/{seleccion}/destroy',[
  'uses'=>'PreguntaSeleccionSimpleController@destroy',
  'as' => 'seleccion-simple.destroy'
]);

Route::resource('falso-verdadero','PreguntaFalsoVerdaderoController');
Route::get('falso-verdadero/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('falso-verdadero/{falsoverdadero}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('falso-verdadero/{falsoverdadero}/destroy',[
  'uses'=>'PreguntaFalsoVerdaderoController@destroy',
  'as' => 'falso-verdadero.destroy'
]);

Route::resource('opciones','SeleccionSimpleOpcionesController');

Route::resource('ordenamiento','PreguntaOrdenamientoController');
Route::get('ordenamiento/{ordenamiento}/edit',[
  'uses'=>'PreguntaOrdenamientoController@edit',
  'as' => 'ordenamiento.edit'
]);
Route::get('ordenamiento/{ordenamiento}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('ordenamiento/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('ordenamiento/{ordenamiento}/destroy',[
  'uses'=>'PreguntaOrdenamientoController@destroy',
  'as' => 'ordenamiento.destroy'
]);
Route::resource('opcionesorden','OrdenamientoOpcionesController');

Route::resource('preguntas/listar','PreguntaFrontController');

Route::resource('seleccion-multiple','PreguntaSeleccionMultipleController');
Route::get('seleccion-multiple/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('seleccion-multiple/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('seleccion-multiple/{seleccion}/destroy',[
  'uses'=>'PreguntaSeleccionMultipleController@destroy',
  'as' => 'seleccion-multiple.destroy'
]);

Route::resource('opciones-multiple','SeleccionMultipleOpcionesController');

Route::resource('correccion-falso-verdadero','RespuestasFalsoVerdaderoController');
Route::get('correccion-falso-verdadero/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('correccion-falso-verdadero/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('correccion-falso-verdadero/{seleccion}/destroy',[
  'uses'=>'RespuestasFalsoVerdaderoController@destroy',
  'as' => 'correccion-falso-verdadero.destroy'
]);

Route::resource('correccion-abiertas','RespuestaPreguntaAbiertaController');
Route::get('correccion-abiertas/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('correccion-abiertas/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('correccion-abiertas/{seleccion}/destroy',[
  'uses'=>'RespuestaPreguntaAbiertaController@destroy',
  'as' => 'correccion-abiertas.destroy'
]);

Route::resource('correccion-sel-simple','RespuestaSeleccionSimpleController');
Route::get('correccion-sel-simple/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('correccion-sel-simple/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('correccion-sel-simple/{seleccion}/destroy',[
  'uses'=>'RespuestaSeleccionSimpleController@destroy',
  'as' => 'correccion-sel-simple.destroy'
]);

Route::resource('correccion-ordenamiento','RespuestaOrdenamientoController');
Route::get('correccion-ordenamiento/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('correccion-ordenamiento/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('correccion-ordenamiento/{seleccion}/destroy',[
  'uses'=>'RespuestaOrdenamientoController@destroy',
  'as' => 'correccion-ordenamiento.destroy'
]);
Route::resource('usuarios','UsuarioController');

Route::resource('login','LoginController');
Route::get('logout','LoginController@logout');
//Mau Trigo

//Roger
Route::resource('respuestaSeleccion','RespuestaSelMultipleController');
Route::get('respuestaSelecion/{id}/create',[
  'uses' => 'RespuestaSelMultipleController@create',
  'as'   => 'respuestaSeleccion.create'
]);
Route::resource('resolver-emparejamiento','CorreccionEmparejamientoController');
Route::get('resolver-emparejamiento/{id}/create',[
  'uses' => 'CorreccionEmparejamientoController@create',
  'as'   => 'resolver-emparejamiento.create'
]);
//Roger

//Daniela
// complementacion

Route::get('/pregunta-complementacion', function(){
    $preguntas = PreguntaComplementacion::all();
    return view('preguntacomplementacion.listar', array(
        'preguntas' => $preguntas
    ));

});

Route::get('/crear-pregunta-complementacion', function( ){
    $categorias = Categoria::all();
     return view('preguntacomplementacion.create', array(
        'categorias' => $categorias
    ));
});

Route::post('/crear-pregunta-complementacion', function(Request $request){
    $rules = array(
        'enunciado' => 'required|max:255|min:6',
    );
    $mensajes = array(
        'required' => 'El campo :attribute es requerido',
        'min' => 'El campo :attribute debe ser mayor a 6 caracteres'

    );
    $validator = Validator::make($request->all(), $rules, $mensajes);
    if($validator->fails()) {
      return redirect('/crear-pregunta-complementacion')
        ->withInput()
        ->withErrors($validator);
    }
    $respuestas = $request->respuestas;
    $rules = array(
        'palabra clave' => 'required',
    );
    for ($i = 0; $i < count($respuestas) ; $i++) {
        $valores = array(
            'palabra clave' => $respuestas[$i],
        );
        $validator = Validator::make($valores, $rules, $mensajes);
        if($validator->fails()) {
            return redirect('/crear-pregunta-complementacion')
            ->withInput()
            ->withErrors($validator);
        }
    }

    $pregunta = new PreguntaComplementacion;
    $pregunta->enunciado = $request->enunciado;
    $pregunta->usuarios_id = $request->usuarios_id;
    if($request->subcategoria) {
        $pregunta->subcategoria_id = $request->subcategoria;
    } else {
        $pregunta->subcategoria_id = null;
    }
    //$pregunta->subcategoria_id = $request->subcategoria;
    $pregunta->save();
    for ($i = 0; $i < count($respuestas) ; $i++) {
        $respuesta = new RespuestaComplementacion;
        $respuesta->respuesta = $respuestas[$i];
        $respuesta->pregunta_complementacion_id = $pregunta->id;
        $respuesta->save();
    }
    return redirect('/ver-pregunta-complementacion/' . $pregunta->id);
});
Route::get('/editar-pregunta-complementacion/{pregunta}', function( PreguntaComplementacion $pregunta ){
    $categorias = Categoria::all();
    return view('preguntacomplementacion.editar', array(
        'pregunta' => $pregunta,
        'categorias' => $categorias
    ));
});

Route::post('/editar-pregunta-complementacion/{pregunta}', function(Request $request, PreguntaComplementacion $pregunta){
    $rules = array(
        'enunciado' => 'required|max:255|min:6',
    );
    $mensajes = array(
        'required' => 'El campo :attribute es requerido',
        'min' => 'El campo :attribute debe ser mayor a 6 caracteres'

    );
    $validator = Validator::make($request->all(), $rules, $mensajes);
    if($validator->fails()) {
      return redirect('/editar-pregunta-complementacion' . $pregunta->id)
        ->withInput()
        ->withErrors($validator);
    }
    $respuestas = $request->respuestas;
    $rules = array(
        'palabra clave' => 'required',
    );
    for ($i = 0; $i < count($respuestas) ; $i++) {
        $valores = array(
            'palabra clave' => $respuestas[$i],
        );
        $validator = Validator::make($valores, $rules, $mensajes);
        if($validator->fails()) {
            return redirect('/editar-pregunta-complementacion' . $pregunta->id)
            ->withInput()
            ->withErrors($validator);
        }
    }

    $pregunta->enunciado = $request->enunciado;
    //$pregunta->subcategoria_id = $request->subcategoria;
    if($request->subcategoria) {
        $pregunta->subcategoria_id = $request->subcategoria;
    } else {
        $pregunta->subcategoria_id = null;
    }
    $pregunta->save();
    foreach ($pregunta->respuestas as $respuesta) {
        $respuesta->delete();
    }

    for ($i = 0; $i < count($respuestas) ; $i++) {
        $respuesta = new RespuestaComplementacion;
        $respuesta->respuesta = $respuestas[$i];

app/PreguntaAbierta.php
<?php

namespace GoTest;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use Storage;
use File;
use DB;

class PreguntaAbierta extends Model
{
  protected $table = "preguntas_abiertas";
  protected $fillable = ['enunciado','respuesta','infopath','categorias_id','sub_categorias_id','tipos_pregunta_id','usuarios_id'];

  public function setInfopathAttribute($infopath){//hace referencia al campo path
    if(!empty($infopath)){
    $name = Carbon::now()->second.$infopath->getClientOriginalName();
    $this->attributes['infopath'] = $name;
    Storage::disk('local')->put($name, File::get($infopath));
  }
  }
  public static function getAll(){
    return DB::table('preguntas_abiertas')
          ->join('categorias','preguntas_abiertas.categorias_id','=','categorias.id')
          ->join('sub_categorias','preguntas_abiertas.sub_categorias_id','=','sub_categorias.id')
          //->join('sub_categorias','sub_categorias.categorias_id','=','categorias.id')
          ->select('preguntas_abiertas.id','preguntas_abiertas.enunciado','preguntas_abiertas.respuesta','categorias.categoria',
                   'sub_categorias.categoria as subcategoria','preguntas_abiertas.infopath','preguntas_abiertas.created_at')
          ->paginate(5);
  }

  public static function getAll_front(){
    return DB::table('preguntas_abiertas')
          ->join('categorias','preguntas_abiertas.categorias_id','=','categorias.id')
          ->join('sub_categorias','preguntas_abiertas.sub_categorias_id','=','sub_categorias.id')
          ->join('tipos_pregunta','preguntas_abiertas.tipos_pregunta_id','=','tipos_pregunta.id')
          //->join('sub_categorias','sub_categorias.categorias_id','=','categorias.id')
          ->select('preguntas_abiertas.id','tipos_pregunta.tipo','tipos_pregunta.alias','preguntas_abiertas.enunciado','preguntas_abiertas.respuesta','categorias.categoria',
                   'sub_categorias.categoria as subcategoria','preguntas_abiertas.created_at')
          ->get();
  }

  public static function getPregunta_detalles($id){
    return DB::select('SELECT p.id,p.enunciado, c.categoria, s.categoria as subcategoria,p.respuesta,p.infopath, p.created_at, p.updated_at
                      FROM sub_categorias s, preguntas_abiertas p, categorias c
                      WHERE p.categorias_id = c.id AND p.sub_categorias_id = s.id AND s.categorias_id = c.id AND p.id = '.$id);
  }
  public static function getRows_count(){
        return DB::table("preguntas_abiertas")->count();         
  }
  public static function getPreguntas_usuario($id){
    return DB::select('SELECT p.id,p.enunciado, c.categoria, s.categoria as subcategoria,p.respuesta,p.infopath, p.created_at, p.updated_at
                      FROM sub_categorias s, preguntas_abiertas p, categorias c, usuarios u
                      WHERE p.categorias_id = c.id AND p.sub_categorias_id = s.id AND s.categorias_id = c.id AND p.usuarios_id = '.$id);
  }
}

app/Http/Controllers/PreguntaAbiertaController.php
<?php

namespace GoTest\Http\Controllers;

use Illuminate\Http\Request;
use GoTest\PreguntaAbierta;
use GoTest\Categoria;
use GoTest\SubCategoria;
use GoTest\Http\Requests;
use GoTest\Http\Requests\AbiertaCreateRequest;
use Session;
use DB;

class PreguntaAbiertaController extends Controller
{
    public function __construct(){
      $this->middleware('usuario',['only'=>['create','store','update','destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $preguntas = PreguntaAbierta::getAll();
        return view('preguntaabierta.index',compact('preguntas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $categorias = Categoria::lists('categoria','id');
      //$subcategorias = SubCategoria::lists('categoria','id');
      return view('preguntaabierta.create',compact('categorias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AbiertaCreateRequest $request)
    {
        PreguntaAbierta::create($request->all());
        Session::flash('store-success','Datos agregados correctamente!');
        return redirect()->route('abierta.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $pregunta1 = PreguntaAbierta::getPregunta_detalles($id);
        $pregunta2 = PreguntaAbierta::find($id);
        $categorias = Categoria::lists('categoria','id');
        return view('preguntaabierta.show',compact('categorias'),['pregunta1'=>$pregunta1,'pregunta2'=>$pregunta2]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $pregunta = PreguntaAbierta::find($id);
      $subcategoria = DB::table('sub_categorias')->select('id','categoria')->where('categorias_id','=',$pregunta->categorias_id)->lists('categoria','id');
      $categoria = Categoria::lists('categoria','id');
      return view('preguntaabierta.edit',['pregunta'=>$pregunta,'categoria'=>$categoria,'subcategoria'=>$subcategoria]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AbiertaCreateRequest $request, $id)
    {
        $pregunta = PreguntaAbierta::find($id);
        $pregunta->enunciado = $request->enunciado;
        $pregunta->respuesta = $request->respuesta;
        $pregunta->infopath = $request->infopath;

        $pregunta->categorias_id = $request->categorias_id;
        $pregunta->sub_categorias_id = $request->sub_categorias_id;
        $pregunta->save();
        Session::flash('update-success','Datos actualizados correctamente!');
        return redirect()->route('abierta.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pregunta = PreguntaAbierta::find($id);
        $pregunta->delete();
        Session::flash('delete-success','Datos eliminados correctamente!');
        return redirect()->route('abierta.index');
    }
}

resources/views/preguntaabierta/create.blade.php
@extends('layouts.principal')
@section('content')
  <div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Registrar pregunta abierta</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- /.row -->
<div class="panel-body">
<div class="row">
    <div class="col-lg-6">

{!!Html::style('css/style2.css')!!}
{!!Form::open(['route'=>'abierta.store', 'method'=>'POST','files' => true])!!}
{!!Form::hidden('usuarios_id', Auth::user()->id)!!}
@include('preguntaabierta.form.pregunta')
{!!Form::close()!!}
</div>
</div>
<!-- /.col-lg-8 -->
<!-- /.col-lg-4 -->
</div>
@include('layouts.scripts')
@endsection

resources/views/preguntaabierta/edit.blade.php
@extends('layouts.principal')
@section('content')
  {!!Form::model($pregunta,['route'=>['abierta.update',$pregunta->id],'method'=>'PUT','files' => true])!!} <!--enrutando los datos -->
  <div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Editar pregunta</h1>
    </div>
</div>
<div class="panel-body">
<div class="row">
    <div class="col-lg-6">
      {!!Html::style('css/style2.css')!!}
      {!!Form::label('categoria','Categoria: ')!!}
      {!!Form::select('categorias_id', $categoria,null,['id'=>'categoriaAbiertas','class'=>'form-control',
                      'placeholder'=>'Seleccione una opcion..','required'])!!}<br>
      {!!Form::label('subcategoria','Sub-categoria: ')!!}
      {!!Form::select('sub_categorias_id', $subcategoria,null,['id'=>'subcategoriaAbiertas','class'=>'form-control',
											'placeholder'=>'Seleccione una opcion..','required'])!!}<br>
      {!!Form::label('enunciado','Enunciado: ')!!}
      @include('alerts.success')
      @include('alerts.required')
      {!!Form::textarea('enunciado',null,['class'=>'form-control', 'rows' => 3,'required']) !!}<br>
      {!!Form::label('respuesta','Respuesta(s) correcta(s): ')!!}
      {!!Form::textarea('respuesta',null,['class'=>'form-control', 'rows' => 3]) !!}<br>
      {!!Form::label('img','Imagen:')!!}
      {!!Form::file('infopath',['enctype'=>'multipart/form-data'])!!}<br>
      <br>{!!Form::submit('Registrar',['class'=>'btn btn-outline btn-primary'])!!}<br><br><br>
      {!!Form::close()!!}
    </div>
    </div>
</div>
@include('layouts.scripts')
@endsection

resources/views/preguntaabierta/index.blade.php
@extends('layouts.principal')
@section('content')
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Preguntas registradas</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Preguntas registradas en la base de datos
        <div class="pull-right">
          <div class="btn-group">
            <a class="glyphicon-plus btn btn-info btn-xs" href="{!!URL::to('abierta/create')!!}"> Crear nueva</a>
          </div>
        </div>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="dataTable_wrapper">
          <table class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
              <tr>
                <th>Enunciado</th>
                <th>Categor&iacute;a</th>
                <th>Sub-categor&iacute;a</th>
                <th>Fecha creaci&oacute;n</th>
                <th>Imagen</th>
                <th>Acci&oacute;n</th>
              </tr>
            </thead>
            {{-- <tbody id="datos"> --}}
              @foreach($preguntas as $pregunta)
              <tbody>
                <tr>
                  <td>{{str_limit($pregunta->enunciado,$limit = 30,$end='...')}}</td>
                  <td>{{$pregunta->categoria}}</td>
                  <td>{{$pregunta->subcategoria}}</td>
                  <td>{{$pregunta->created_at}}</td>
                  @if($pregunta->infopath == null)
                  <td><img src="infopath/no-image.jpg" alt="" style="width:100px"/></td>
                  <td><div class="form-group" align="center"><a href="{!! route('abierta.show',$parameters = $pregunta->id) !!}" class="btn btn-success btn-circle" data-tooltip="Ver detalle"><i class="fa fa-search"></i></a>
                  <a href="{!! route('abierta.edit',$parameters = $pregunta->id) !!}" class="btn btn-primary btn-circle" data-tooltip="Editar pregunta"><i class="glyphicon glyphicon-edit"></i></a>
                  <a href="{!! route('correccion-abiertas.show',$parameters = $pregunta->id) !!}" class="btn btn-warning btn-circle" data-tooltip="Resolver y corregir"><i class="fa fa-mortar-board "></i></a>
                  <a href="{!! route('abierta.destroy',$parameters = $pregunta->id) !!}" class="btn btn-danger btn-circle" data-tooltip="Eliminar pregunta" onclick='return confirm("¿Estas seguro de querer eliminar?")'><i class="glyphicon glyphicon-trash"></i></a></div>
                </td>
                @else
                <td><img src="infopath/{{$pregunta->infopath}}" alt="" style="width:100px"/></td>
                <td>
                  <div class="form-group" align="center"><a href="{!! route('abierta.show',$parameters = $pregunta->id) !!}" class="btn btn-success btn-circle" data-tooltip="Ver detalle"><i class="fa fa-search"></i></a>
                  <a href="{!! route('abierta.edit',$parameters = $pregunta->id) !!}" class="btn btn-primary btn-circle" data-tooltip="Editar pregunta"><i class="glyphicon glyphicon-edit"></i></a>
                  <a href="{!! route('correccion-abiertas.show',$parameters = $pregunta->id) !!}" class="btn btn-warning btn-circle" data-tooltip="Resolver y corregir"><i class="fa fa-mortar-board "></i></a>
                  <a href="{!! route('abierta.destroy',$parameters = $pregunta->id) !!}" class="btn btn-danger btn-circle" data-tooltip="Eliminar pregunta" onclick='return confirm("¿Estas seguro de querer eliminar?")'><i class="glyphicon glyphicon-trash"></i></a></div>
                </td>
                @endif
              </tr>
            </tbody>
            @endforeach
          {{-- </tbody> --}}
        </table>
        {!!$preguntas->render()!!}
        @include('alerts.success')
        @include('alerts.required')
      </div>
    </div>
  </div>
</div>
</div>
@endsection

resources/views/preguntaabierta/show.blade.php
@extends('layouts.principal')
@section('content')
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Detalles de la pregunta</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- /.row -->
<div class="panel-body">
  <div class="row">
    <div class="col-lg-10">
      <?php
      $enunciado = $pregunta1[0]->enunciado;
      $categoria = $pregunta1[0]->categoria;
      $subcategoria = $pregunta1[0]->subcategoria;
      $respuesta_original = $pregunta1[0]->respuesta;
      $infopath = $pregunta2->infopath;
      $created_at = $pregunta1[0]->created_at;
      $updated_at = $pregunta1[0]->updated_at;
      ?>
      <div class="table-responsive table-bordered">
        <table class="table">
          <thead>
            <tr>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><h4><b>Enunciado: </b></h4></td>
              <td><h5>{{ $enunciado }}</h5></td>
            </tr>
            <tr>
              <td><h4><b>Categor&iacute;a: </b></h4></td>
              <td><h5>{{ $categoria }}</h5></td>
            </tr>
            <tr>
              <td><h4><b>Sub-categor&iacute;a: </b></h4></td>
              <td><h5>{{ $subcategoria }}</h5></td>
            </tr>
            <tr>
              <td><h4><b>Imagen: </b></h4></td>
              <td>@if($infopath == null)
                <img src="http://globalsystem.cs.umss.edu.bo/infopath/no-image.jpg" border="4" style="width:240px" />
                @else
                <img src="http://globalsystem.cs.umss.edu.bo/infopath/{{ $infopath }}" style="width:240px" />
                @endif
              </td>
            </tr>
            <td><h4><b>Respuesta: </b></h4></td>
            <td>
              @if($respuesta_original == '')
              <h4><p class="text-danger" >Sin respuesta</p></h4>
              @else
              <h4><p class="text-success" >{{ $respuesta_original }}</p></h4>
              @endif
            </td>
          </tr>
          <tr>
            <td><h4><b>Puntaje o valor: </b></h4></td>
            <td>
              <h5><p class="text-danger" >Puntuaci&oacute;n no definida por el sistema.</p></h5>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <h1 class="page-header"></h1>
    <a href="{!! URL::to('abierta') !!}" class="btn btn-primary"> Regresar<i class="fa fa-back"></i></a><br><br><br><br>
  </div>
</div>
</div>
@include('layouts.scripts')
@endsection