app/Http/routes.php
<?php
use Illuminate\Http\Request;
use GoTest\PreguntaOrden;
use GoTest\RespuestaOrden;
use GoTest\PreguntaComplementacion;
use GoTest\RespuestaComplementacion;
use GoTest\Categoria;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//Mauricio Trigo
Route::resource('/', 'HomeController');
Route::get('/home','HomeController@home');
Route::resource('pregunta','PreguntaFrontController');
Route::get('pregunta/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');


Route::resource('abierta','PreguntaAbiertaController');
Route::get('abierta/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('abierta/{abierta}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('abierta/{abierta}/destroy',[
  'uses'=>'PreguntaAbiertaController@destroy',
  'as' => 'abierta.destroy'
]);

Route::get('subcategoria/{subcategoria}','CategoriaController@getSubCategorias');

Route::resource('seleccion-simple','PreguntaSeleccionSimpleController');
Route::get('seleccion-simple/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('seleccion-simple/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('seleccion-simple/{seleccion}/destroy',[
  'uses'=>'PreguntaSeleccionSimpleController@destroy',
  'as' => 'seleccion-simple.destroy'
]);

Route::resource('falso-verdadero','PreguntaFalsoVerdaderoController');
Route::get('falso-verdadero/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('falso-verdadero/{falsoverdadero}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('falso-verdadero/{falsoverdadero}/destroy',[
  'uses'=>'PreguntaFalsoVerdaderoController@destroy',
  'as' => 'falso-verdadero.destroy'
]);

Route::resource('opciones','SeleccionSimpleOpcionesController');

Route::resource('ordenamiento','PreguntaOrdenamientoController');
Route::get('ordenamiento/{ordenamiento}/edit',[
  'uses'=>'PreguntaOrdenamientoController@edit',
  'as' => 'ordenamiento.edit'
]);
Route::get('ordenamiento/{ordenamiento}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('ordenamiento/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('ordenamiento/{ordenamiento}/destroy',[
  'uses'=>'PreguntaOrdenamientoController@destroy',
  'as' => 'ordenamiento.destroy'
]);
Route::resource('opcionesorden','OrdenamientoOpcionesController');

Route::resource('preguntas/listar','PreguntaFrontController');

Route::resource('seleccion-multiple','PreguntaSeleccionMultipleController');
Route::get('seleccion-multiple/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('seleccion-multiple/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('seleccion-multiple/{seleccion}/destroy',[
  'uses'=>'PreguntaSeleccionMultipleController@destroy',
  'as' => 'seleccion-multiple.destroy'
]);

Route::resource('opciones-multiple','SeleccionMultipleOpcionesController');

Route::resource('correccion-falso-verdadero','RespuestasFalsoVerdaderoController');
Route::get('correccion-falso-verdadero/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('correccion-falso-verdadero/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('correccion-falso-verdadero/{seleccion}/destroy',[
  'uses'=>'RespuestasFalsoVerdaderoController@destroy',
  'as' => 'correccion-falso-verdadero.destroy'
]);

Route::resource('correccion-abiertas','RespuestaPreguntaAbiertaController');
Route::get('correccion-abiertas/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('correccion-abiertas/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('correccion-abiertas/{seleccion}/destroy',[
  'uses'=>'RespuestaPreguntaAbiertaController@destroy',
  'as' => 'correccion-abiertas.destroy'
]);

Route::resource('correccion-sel-simple','RespuestaSeleccionSimpleController');
Route::get('correccion-sel-simple/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('correccion-sel-simple/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('correccion-sel-simple/{seleccion}/destroy',[
  'uses'=>'RespuestaSeleccionSimpleController@destroy',
  'as' => 'correccion-sel-simple.destroy'
]);

Route::resource('correccion-ordenamiento','RespuestaOrdenamientoController');
Route::get('correccion-ordenamiento/subcategoria/{subcategoria}','CategoriaController@getSubCategorias');
Route::get('correccion-ordenamiento/{seleccion}/subcategoria/{subcategoria}','CategoriaController@getSubCategorias2');
Route::get('correccion-ordenamiento/{seleccion}/destroy',[
  'uses'=>'RespuestaOrdenamientoController@destroy',
  'as' => 'correccion-ordenamiento.destroy'
]);
Route::resource('usuarios','UsuarioController');

Route::resource('login','LoginController');
Route::get('logout','LoginController@logout');
//Mau Trigo

//Roger
Route::resource('respuestaSeleccion','RespuestaSelMultipleController');
Route::get('respuestaSelecion/{id}/create',[
  'uses' => 'RespuestaSelMultipleController@create',
  'as'   => 'respuestaSeleccion.create'
]);
Route::resource('resolver-emparejamiento','CorreccionEmparejamientoController');
Route::get('resolver-emparejamiento/{id}/create',[
  'uses' => 'CorreccionEmparejamientoController@create',
  'as'   => 'resolver-emparejamiento.create'
]);
//Roger

//Daniela
// complementacion

Route::get('/pregunta-complementacion', function(){
    $preguntas = PreguntaComplementacion::all();
    return view('preguntacomplementacion.listar', array(
        'preguntas' => $preguntas
    ));

});

Route::get('/crear-pregunta-complementacion', function( ){
    $categorias = Categoria::all();
     return view('preguntacomplementacion.create', array(
        'categorias' => $categorias
    ));
});

Route::post('/crear-pregunta-complementacion', function(Request $request){
    $rules = array(
        'enunciado' => 'required|max:255|min:6',
    );
    $mensajes = array(
        'required' => 'El campo :attribute es requerido',
        'min' => 'El campo :attribute debe ser mayor a 6 caracteres'

    );
    $validator = Validator::make($request->all(), $rules, $mensajes);
    if($validator->fails()) {
      return redirect('/crear-pregunta-complementacion')
        ->withInput()
        ->withErrors($validator);
    }
    $respuestas = $request->respuestas;
    $rules = array(
        'palabra clave' => 'required',
    );
    for ($i = 0; $i < count($respuestas) ; $i++) {
        $valores = array(
            'palabra clave' => $respuestas[$i],
        );
        $validator = Validator::make($valores, $rules, $mensajes);
        if($validator->fails()) {
            return redirect('/crear-pregunta-complementacion')
            ->withInput()
            ->withErrors($validator);
        }
    }

    $pregunta = new PreguntaComplementacion;
    $pregunta->enunciado = $request->enunciado;
    $pregunta->usuarios_id = $request->usuarios_id;
    if($request->subcategoria) {
        $pregunta->subcategoria_id = $request->subcategoria;
    } else {
        $pregunta->subcategoria_id = null;
    }
    //$pregunta->subcategoria_id = $request->subcategoria;
    $pregunta->save();
    for ($i = 0; $i < count($respuestas) ; $i++) {
        $respuesta = new RespuestaComplementacion;
        $respuesta->respuesta = $respuestas[$i];
        $respuesta->pregunta_complementacion_id = $pregunta->id;
        $respuesta->save();
    }
    return redirect('/ver-pregunta-complementacion/' . $pregunta->id);
});
Route::get('/editar-pregunta-complementacion/{pregunta}', function( PreguntaComplementacion $pregunta ){
    $categorias = Categoria::all();
    return view('preguntacomplementacion.editar', array(
        'pregunta' => $pregunta,
        'categorias' => $categorias
    ));
});

Route::post('/editar-pregunta-complementacion/{pregunta}', function(Request $request, PreguntaComplementacion $pregunta){
    $rules = array(
        'enunciado' => 'required|max:255|min:6',
    );
    $mensajes = array(
        'required' => 'El campo :attribute es requerido',
        'min' => 'El campo :attribute debe ser mayor a 6 caracteres'

    );
    $validator = Validator::make($request->all(), $rules, $mensajes);
    if($validator->fails()) {
      return redirect('/editar-pregunta-complementacion' . $pregunta->id)
        ->withInput()
        ->withErrors($validator);
    }
    $respuestas = $request->respuestas;
    $rules = array(
        'palabra clave' => 'required',
    );
    for ($i = 0; $i < count($respuestas) ; $i++) {
        $valores = array(
            'palabra clave' => $respuestas[$i],
        );
        $validator = Validator::make($valores, $rules, $mensajes);
        if($validator->fails()) {
            return redirect('/editar-pregunta-complementacion' . $pregunta->id)
            ->withInput()
            ->withErrors($validator);
        }
    }

    $pregunta->enunciado = $request->enunciado;
    //$pregunta->subcategoria_id = $request->subcategoria;
    if($request->subcategoria) {
        $pregunta->subcategoria_id = $request->subcategoria;
    } else {
        $pregunta->subcategoria_id = null;
    }
    $pregunta->save();
    foreach ($pregunta->respuestas as $respuesta) {
        $respuesta->delete();
    }

    for ($i = 0; $i < count($respuestas) ; $i++) {
        $respuesta = new RespuestaComplementacion;
        $respuesta->respuesta = $respuestas[$i];

app/PreguntaSeleccion.php
<?php

namespace GoTest;

use Illuminate\Database\Eloquent\Model;
use DB;
//
class PreguntaSeleccion extends Model
{
  protected $table = "preguntas_seleccion";
  protected $fillable = ['tipo','enunciado','seleccion_opciones_id','categorias_id','sub_categorias_id','usuarios_id'];

  public static function getAll(){
    return DB::table('preguntas_seleccion')
          ->join('categorias','preguntas_seleccion.categorias_id','=','categorias.id')
          ->join('sub_categorias','preguntas_seleccion.sub_categorias_id','=','sub_categorias.id')
          //->join('sub_categorias','sub_categorias.categorias_id','=','categorias.id')
          ->select('preguntas_seleccion.id','preguntas_seleccion.enunciado','categorias.categoria',
                   'sub_categorias.categoria as subcategoria','preguntas_seleccion.created_at')
          ->paginate(2);
  }
  public function opciones(){
    return $this->hasMany('GoTest\SeleccionOpciones', 'preguntas_seleccion_id');
  }
  public function respuestasSelMultiple(){
    return $this->hasMany('GoTest\RespuestaSelMultiple', 'preguntas_seleccion_id');
  }
}

app/Http/Controllers/PreguntaSeleccionController.php
<?php

namespace GoTest\Http\Controllers;

use Illuminate\Http\Request;
use GoTest\SeleccionOpciones;
use GoTest\PreguntaSeleccion;
use GoTest\Http\Requests;
use GoTest\Categoria;
use GoTest\SubCategoria;
use Session;
use DB;
use Validator;

class PreguntaSeleccionController extends Controller
{
    public function __construct(){
      $this->middleware('usuario',['only'=>['create','store','update','destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $preguntas = PreguntaSeleccion::getAll();
      return view('preguntaseleccion.index',compact('preguntas'));
      //dd($preguntas);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //return view('preguntaseleccion.create');
        //return redirect()-route('pregunta.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {



        PreguntaSeleccion::create($request->all());
        // ULTIMO REGISTRO Esto me regresa el campo como un arreglo y puedo accederlo como un string ->first()
        $tupla = DB::table('preguntas_seleccion')->select('id')
                                                 ->orderBy('created_at', 'desc')
                                                 ->take('1')
                                                 ->first();
        // OK
        $preguntas_seleccion_id = $tupla->id;
        $opcionesSelect = $request->opcion;
        $correctosSelect = $request->correcto;

        for($i = 0; $i < count($opcionesSelect); $i++){
          $opciones = new SeleccionOpciones();
          $opciones->opcion = $opcionesSelect[$i];
          if($correctosSelect[$i] == '0'){
            $opciones->correcto = 0;
            $opciones->peso = 0;
          }else{
           $opciones->correcto = 1;
           $opciones->peso = 100;
          }
          $opciones->preguntas_seleccion_id = $preguntas_seleccion_id;
          $opciones->save();
        }
        
        Session::flash('store-success','Datos agregados correctamente!');
        return redirect()->route('seleccion.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $pregunta = PreguntaSeleccion::find($id);
      $subcategoria = DB::table('sub_categorias')->select('id','categoria')->where('categorias_id','=',$pregunta->categorias_id)->lists('categoria','id');
      $categoria = Categoria::lists('categoria','id');
      $obj = new SeleccionOpciones();
      $opcion = SeleccionOpciones::where('preguntas_seleccion_id','=',$pregunta->id)->get();
      $correcto = $obj->getCorrectos($id);
      return view('preguntaseleccion.edit',['pregunta'=>$pregunta,'categoria'=>$categoria,
      'subcategoria'=>$subcategoria,'opcion'=>$opcion]);
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $pregunta = PreguntaSeleccion::find($id);
        $pregunta->enunciado = $request->enunciado;
        $pregunta->categorias_id = $request->categorias_id;
        $pregunta->sub_categorias_id = $request->sub_categorias_id;
        $pregunta->save();
        $array = $request->id_opciones;
        for($i = 0; $i < count($array); $i++){
          $opcionObj = SeleccionOpciones::find($array[$i]);
          $opcionObj->opcion = $request->opcion[$i];
          $opcionObj->correcto = $request->correcto[$i];
          $opcionObj->save();
        }
        if(isset($request->correcto2) && isset($request->opcion2)){//NUEVOS CAMPOS AGREGADOS
          for($i = 0; $i < count($request->correcto2); $i++){
            $nuevoCampo = new SeleccionOpciones();
            $nuevoCampo->opcion = $request->opcion2[$i];
            $nuevoCampo->correcto = $request->correcto2[$i];
            $nuevoCampo->preguntas_seleccion_id = $id;
            $nuevoCampo->save();
          }
        }
        Session::flash('update-success','Datos actualizados correctamente!');
        return redirect()->route('seleccion.index');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //eliminacion en cascada
        $pregunta = PreguntaSeleccion::find($id);
        $pregunta->delete();
        Session::flash('delete-success','Datos eliminados correctamente!');
        return redirect()->route('seleccion.index');
    }
}

resources/views/preguntaseleccion/respuesta/index.blade.php
@extends('layouts.principal')
@section('content')
  <div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">Correccion de Respuestas</h1>
  </div>
  <!-- /.col-lg-12 -->
  </div>
  <div class="row">
      <div class="col-lg-12">
          <div class="panel panel-default">
              <div class="panel-heading">
                  Respuestas registradas en la base de datos
              </div>
              <!-- /.panel-heading -->
              <div class="panel-body">
                  <div class="dataTable_wrapper">
                      <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                              <tr>
                                  <th>Pregunta</th>
                                  <th>Respuesta</th>
                                  <th>Correccion</th>

                              </tr>
                          </thead>
                          {{-- <tbody id="datos"> --}}
                            @foreach($preguntas->respuestasSelMultiple as $pregunta)
                            <tbody>
                              @foreach($respuestas as $respuesta)
                                  <tr>

                                      <td>{{$pregunta->enunciado}}</td>

                                        <td>{{$respuesta->respuesta}}</td>
                                        <td>{{$respuesta->correcto}}</td>


                                  </tr>
                              @endforeach
                            </tbody>
                            @endforeach
                          {{-- </tbody> --}}
                      </table>

                      @include('alerts.success')
                      @include('alerts.required')
                  </div>
              </div>
            </div>
          </div>
        </div>
@endsection

resources/views/preguntaseleccion/respuesta/resolver.blade.php
@extends('layouts.principal')
@section('content')
  <div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">Preguntas registradas</h1>
  </div>
  <!-- /.col-lg-12 -->
  </div>
  <div class="row">
      <div class="col-lg-12">
          <div class="panel panel-default">
              <div class="panel-heading">
                  Preguntas registradas en la base de datos
                  <div class="pull-right">
                                <div class="btn-group">
                                    <a class="glyphicon-plus btn btn-outline btn-info btn-xs" href="{!!URL::to('seleccion-simple/create')!!}"> Crear nueva</a>
                                </div>
                            </div>
                  </button>
              </div>
              <!-- /.panel-heading -->
              <div class="panel-body">
                  <div class="dataTable_wrapper">
                      <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                              <tr>
                                  <th>Enunciado</th>
                                  <th>Categoria</th>
                                  <th>Sub-categoria</th>
                                  <th>Fecha creacion</th>
                                  <th>Accion</th>
                              </tr>
                          </thead>
                          {{-- <tbody id="datos"> --}}
                            @foreach($preguntas as $pregunta)
                            <tbody>
                            <tr>
                              <td>{{str_limit($pregunta->enunciado,$limit = 30,$end='...')}}</td>
                              <td>{{$pregunta->categoria}}</td>
                              <td>{{$pregunta->subcategoria}}</td>
                              <td>{{$pregunta->created_at}}</td>
                              <td>{!!link_to_route('respuestaSeleccion.create', $title = 'Resolver', $parameters = $pregunta->id, $attributes = ['class'=>'btn btn-outline btn-primary'])!!}

                             </td>
                            </tr>
                            </tbody>
                            @endforeach
                          {{-- </tbody> --}}
                      </table>
                      {!!$preguntas->render()!!}
                      @include('alerts.success')
                      @include('alerts.required')
                  </div>
              </div>
            </div>
          </div>
        </div>
@endsection

resources/views/preguntaseleccion/respuesta/show.blade.php
@extends('layouts.principal')
@section('content')
<div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">Correccion de la Pregunta</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- /.row -->
<div class="panel-body">
<div class="row">
  <div class="col-lg-12">
    @include('alerts.success')
    @include('alerts.required')

                              {!! csrf_field() !!}



                                  <div class="panel panel-default">
                                      <div class="panel-heading">
                                          {{ $pregunta->enunciado }}
                                      </div>
                                      <!-- /.panel-heading -->
                                      <div class="panel-body">
                                          <div class="dataTable_wrapper">
                                              <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                                <thead>
                                                      <tr>

                                                          <th>Respuesta</th>
                                                          <th>Correcto</th>

                                                      </tr>
                                                  </thead>
                                                  {{-- <tbody id="datos"> --}}
                                                    @foreach($pregunta->respuestasSelMultiple as $respuesta)
                                                    <tbody>

                                                          <tr>

                                                            @if($respuesta->correcto == 1)
                                                              <div class="">
                                                                <td><span class="label label-primary">{{ $respuesta->respuesta }}</span></td>
                                                              </div>
                                                            @else
                                                              <div class="">
                                                                <td><span class="label label-danger">{{ $respuesta->respuesta }}</span></td>
                                                              </div>
                                                            @endif
                                                            @if($respuesta->correcto == 1)
                                                              <div class="">
                                                                <td><span class="label label-primary">Correcto</span></td>
                                                              </div>
                                                            @else
                                                              <div class="">
                                                                <td><span class="label label-danger">Incorrecto</span></td>
                                                              </div>
                                                            @endif

                                                          </tr>

                                                    </tbody>
                                                    @endforeach
                                                  {{-- </tbody> --}}
                                              </table>

                                              @include('alerts.success')
                                              @include('alerts.required')
                                          </div>
                                      </div>
                                    </div>

                              </div>

                              <br>
                              {!!link_to_route('respuestaSeleccion.index', $title = 'Volver a Pregutnas', null, $attributes = ['class'=>'btn btn-outline btn-primary'])!!}

  </div>
  </div>
  <!-- /.col-lg-8 -->
  <!-- /.col-lg-4 -->
</div>

<!-- /.row -->
{!!Html::script('bower_components/jquery/dist/jquery.min.js')!!}
<!-- Bootstrap Core JavaScript -->
{!!Html::script('bower_components/bootstrap/dist/js/bootstrap.min.js')!!}
<!-- Metis Menu Plugin JavaScript -->
{!!Html::script('bower_components/metisMenu/dist/metisMenu.min.js')!!}
<!-- Morris Charts JavaScript -->
{!!Html::script('bower_components/raphael/raphael-min.js')!!}
{!!Html::script('bower_components/morrisjs/morris.min.js')!!}
{!!Html::script('js/morris-data.js')!!}
<!-- Custom Theme JavaScript -->
{!!Html::script('dist/js/sb-admin-2.js')!!}
@endsection